version: '3'
services:
  nginx-inventorymanager:
    container_name: invmngr
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ../app/build/:/var/www/html/
      - ../app/src/php/:/var/www/html/php/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php-inventorymanager:
      container_name: php.invmngr
      image: php:php-mysql-pdo
      build: ./php/
      volumes:
      - ../app/build/:/var/www/html/
      - ../app/src/php/:/var/www/html/php/
      - ../data/:/var/userdata/
  mysql-inventorymanager:
    container_name: mysql.invmngr
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: accounting
      MYSQL_PASSWORD: accountingpassword
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d
      - ../data/:/var/userdata/
      - ../saves:/saves
